name: Rust

on:
  pull_request:
    branches: [ "production" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose

  clippy:

    runs-on: ubuntu-latest

    steps:
      - name: rust-clippy-check
        uses: actions-rs/clippy-check@v1.0.7
