name: Rust

on:
  push:
    branches:
      - '**'
      - '!production'
  pull_request:
    branches: [ "production" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose

  clippy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.CICD_TOKEN }}
          args: --all-features
